# ─────────────────────────────────────────────────────────────────────────────
#  Nandoroid Shell: Main Hyprland Configuration
# ─────────────────────────────────────────────────────────────────────────────

# --- Source Modular Configs ---
source = ./configs/env.conf
source = ./configs/execs.conf
source = ./configs/general.conf
source = ./configs/rules.conf
source = ./configs/keybinds.conf

# --- Source Nandoroid Shell Keybinds & Rules ---
source = ~/.config/hypr/nandoroid/nandoroid.conf
source = ~/.config/hypr/nandoroid/user_persistence.conf

# --- Monitors ---
monitor=,preferred,auto,1
